# Generated by Django 5.2.5 on 2026-09-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('excerpt', models.TextField(max_length=300, verbose_name='bajada')),
                ('content', models.TextField(verbose_name='contenido')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='imagen de portada')),
                ('category', models.CharField(default='Ideas', max_length=80, verbose_name='categoría')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última edición')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('body', models.TextField(max_length=600, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='entrada')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['created_at'],
            },
        ),
    ]
